# These substitutions allow the end user to override certain values
substitutions:
  name: "esp-cots"
  friendly_name: "ESP COTS"

esp8266:
  board: nodemcu

esphome:
  name: "${name}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: triodes.esp-cots
    version: "0.7"

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

http_request:
  verify_ssl: False

# OTA is required for Over-the-Air updating
ota:
  platform: http_request

update:
  - platform: http_request
    name: "Firmware Update"
    source: "https://github.com/triodes/esp-cots/releases/latest/download/manifest.json"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://triodes/esp-cots/test.yaml@main
  import_full_config: true # or true

wifi:
  # Set up a wifi access point
  ap:
    ssid: "${friendly_name}"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

factory_reset:

button:
  - platform: factory_reset
    name: Factory Reset
  - platform: restart
    name: Restart

output:
  - platform: esp8266_pwm
    pin: GPIO16
    id: led
    inverted: true
    min_power: 0.0001
    zero_means_zero: True

light:
  - platform: monochromatic
    id: led_onboard
    name: Onboard LED
    output: led